# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion-deployment
spec:
  replicas: 3 # Puedes ajustar esto entre 3 y 5 réplicas
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
        - name: mi-aplicacion-container
          image: quirogaagu/ubuntu-apache:1
          ports:
            - containerPort: 80

